name: apollo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio
  - argon2-cffi
  - async_generator
  - attrs
  - babel
  - backcall
  - blas
  - bleach
  - boost
  - boost-cpp
  - brotlipy
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - cryptography
  - cycler
  - defusedxml
  - entrypoints
  - fontconfig
  - freetype
  - gettext
  - greenlet
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg=9b
  - json5
  - jsonschema
  - jupyter-packaging
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - lcms2
  - libblas
  - libcblas
  - libcxx
  - libffi
  - libgfortran5
  - libglib
  - libiconv
  - liblapack
  - libpng
  - libsodium
  - libtiff
  - libuv
  - libxml2
  - llvm-openmp
  - lz4-c
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - ninja
  - notebook
  - numpy
  - olefile
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - prometheus_client
  - prompt-toolkit
  - ptyprocess
  - pycairo
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - pyzmq
  - rdkit
  - readline
  - reportlab
  - requests
  - send2trash
  - setuptools
  - six
  - sniffio
  - sqlalchemy
  - sqlite
  - terminado
  - testpath
  - tk
  - torchaudio
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - urllib3
  - voila
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - appnope
      - ase
      - click
      - decorator
      - h5py
      - isodate
      - joblib
      - llvmlite
      - networkx
      - numba
      - python-louvain
      - rdflib
      - scikit-learn
      - scipy
      - threadpoolctl
      - tqdm
      - xlsxwriter
      - torch-scatter
      - torch-sparse
      - torch-spline-conv
      - torch-geometric
